spring:
  jmx:
    enabled: false
  application:
    name: service-discovery
  profiles:
    active: local
server:
  port: 8081

eureka:
  server:
    metrics:
      enabled: true
  dashboard:
    enabled: false
    path: /dashboard
  client:
    register-with-eureka: false # disable self-registry
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /private
      exposure.include: info,health,prometheus
      path-mapping.prometheus: /metrics
  info:
    java:
      enabled: true
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      netflix:
        discovery: INFO
        eureka: INFO
