name: Functional tests

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  functional-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: App jar
          path: sd-app/build/libs/service-discovery.jar

      - name: Start Spring Boot app
        run: java -jar sd-app/build/libs/service-discovery.jar &

      - name: Wait for Spring Boot to start
        run: |
          echo "Waiting for Spring Boot to start..."
          sleep 3

      - name: Run functional tests
        run: ./gradlew --no-daemon :sd-ft:cucumber

      - name: Stop Spring Boot app
        run: |
          echo "Stopping Spring Boot app..."
          pkill -f 'java -jar sd-app/build/libs/service-discovery.jar'

      - name: Archive Cucumber test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: cucumber-tests-report
            path: |
                sd-ft/reports/cucumber-report.html
