name: Build and test

on:
  push:
    branches: [ master ]
    paths:
      - service-discovery-app/**
      - service-discovery-ft/**
  pull_request:
    branches: [ master ]
    paths:
      - service-discovery-app/**
      - service-discovery-ft/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build Service Discovery module
        run: ./gradlew --no-daemon :service-discovery-app:build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Run unit tests
        run: ./gradlew --no-daemon :service-discovery-app:test
      - name: Run functional tests
        run: ./gradlew --no-daemon :service-discovery-ft:cucumber
