name: Build and test

on:
  push:
    branches: [ main ]
    paths:
      - service-discovery-app/**
      - service-discovery-ft/**
      - gradle/libs.versions.toml
  pull_request:
    branches: [ main ]
    paths:
      - service-discovery-app/**
      - service-discovery-ft/**
      - gradle/libs.versions.toml
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build + unit tests
        run: ./gradlew --no-daemon :service-discovery-app:build

      - name: Start Spring Boot app
        run: java -jar service-discovery-app/build/libs/service-discovery.jar &

      - name: Wait for Spring Boot to start
        run: |
          echo "Waiting for Spring Boot to start..."
          sleep 5

      - name: Run functional tests
        run: ./gradlew --no-daemon :service-discovery-ft:cucumber

      - name: Stop Spring Boot app
        run: |
          echo "Stopping Spring Boot app..."
          pkill -f 'java -jar service-discovery-app/build/libs/service-discovery.jar'