name: Build and test

on:
  push:
    branches: [ main ]
    paths:
      - sd-app/**
      - sd-ft/**
      - gradle/libs.versions.toml
  pull_request:
    branches: [ main ]
    paths:
      - sd-app/**
      - sd-ft/**
      - gradle/libs.versions.toml
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build + unit tests
        run: ./gradlew --no-daemon :sd-app:build

      - name: Archive unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: |
            sd-app/build/reports/tests/test/**/*

      - name: Start Spring Boot app
        run: java -jar sd-app/build/libs/service-discovery.jar &

      - name: Wait for Spring Boot to start
        run: |
          echo "Waiting for Spring Boot to start..."
          sleep 3

      - name: Run functional tests
        run: ./gradlew --no-daemon :sd-ft:cucumber

      - name: Stop Spring Boot app
        run: |
          echo "Stopping Spring Boot app..."
          pkill -f 'java -jar sd-app/build/libs/service-discovery.jar'

      - name: Archive Cucumber test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: cucumber-tests-report
            path: |
                sd-ft/reports/cucumber-report.html
