name: Sonarcloud analyses

on:
  push:
    branches: [ main ]
    paths:
      - 'gradle/**'
      - '**.gradle'
      - 'gradle.properties'
      - 'sd-app/**'
      - 'sd-ft/**'
      - 'lombok.config'
      - '.github/workflows/sonarcloud-analyses.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'gradle/**'
      - '**.gradle'
      - 'gradle.properties'
      - 'sd-app/**'
      - 'sd-ft/**'
      - 'lombok.config'
      - '.github/workflows/sonarcloud-analyses.yml'

jobs:
  sonar-analyses:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info
